export const vehicles = [{
    ID: 1,
    patente: 'AA 128 ZS',
    estado: 'OK',
    km: '29.000',
    lugar: 'Predio',
    ImageSrc: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/2016_Toyota_RAV4_%28ASA44R_MY16%29_GX_wagon_%282017-01-15%29_01.jpg',
}, 
{
    ID: 2,
    patente: 'ZFV 443',
    estado: 'Deteriorado',
    km: '500.000',
    lugar: 'Predio',
    ImageSrc: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Fiat_600_Standard_1959.jpg',
}, 
// {
//     ID: 3,
//     Name: 'SuperPlasma 50',
//     Price: 2400,
//     Current_Inventory: 0,
//     Backorder: 0,
//     Manufacturing: 0,
//     Category: 'Televisions',
//     ImageSrc: 'images/vehicles/3.png',
// }, {
//     ID: 4,
//     Name: 'SuperLED 50',
//     Price: 1600,
//     Current_Inventory: 77,
//     Backorder: 0,
//     Manufacturing: 55,
//     Category: 'Televisions',
//     ImageSrc: 'images/vehicles/4.png',
// }, {
//     ID: 5,
//     Name: 'SuperLED 42',
//     Price: 1450,
//     Current_Inventory: 445,
//     Backorder: 0,
//     Manufacturing: 0,
//     Category: 'Televisions',
//     ImageSrc: 'images/vehicles/5.png',
// }, {
//     ID: 6,
//     Name: 'SuperLCD 55',
//     Price: 1350,
//     Current_Inventory: 345,
//     Backorder: 0,
//     Manufacturing: 5,
//     Category: 'Televisions',
//     ImageSrc: 'images/vehicles/6.png',
// }, {
//     ID: 7,
//     Name: 'SuperLCD 42',
//     Price: 1200,
//     Current_Inventory: 210,
//     Backorder: 0,
//     Manufacturing: 20,
//     Category: 'Televisions',
//     ImageSrc: 'images/vehicles/7.png',
// }, {
//     ID: 8,
//     Name: 'SuperPlasma 65',
//     Price: 3500,
//     Current_Inventory: 0,
//     Backorder: 0,
//     Manufacturing: 0,
//     Category: 'Televisions',
//     ImageSrc: 'images/vehicles/8.png',
// }, {
//     ID: 9,
//     Name: 'SuperLCD 70',
//     Price: 4000,
//     Current_Inventory: 95,
//     Backorder: 0,
//     Manufacturing: 5,
//     Category: 'Televisions',
//     ImageSrc: 'images/vehicles/9.png',
// }, {
//     ID: 10,
//     Name: 'DesktopLED 21',
//     Price: 175,
//     Current_Inventory: null,
//     Backorder: 425,
//     Manufacturing: 75,
//     Category: 'Monitors',
//     ImageSrc: 'images/vehicles/10.png',
// }, {
//     ID: 12,
//     Name: 'DesktopLCD 21',
//     Price: 170,
//     Current_Inventory: 210,
//     Backorder: 0,
//     Manufacturing: 60,
//     Category: 'Monitors',
//     ImageSrc: 'images/vehicles/12.png',
// }, {
//     ID: 13,
//     Name: 'DesktopLCD 19',
//     Price: 160,
//     Current_Inventory: 150,
//     Backorder: 0,
//     Manufacturing: 210,
//     Category: 'Monitors',
//     ImageSrc: 'images/vehicles/13.png',
// }, {
//     ID: 14,
//     Name: 'Projector Plus',
//     Price: 550,
//     Current_Inventory: null,
//     Backorder: 55,
//     Manufacturing: 10,
//     Category: 'Projectors',
//     ImageSrc: 'images/vehicles/14.png',
// }, {
//     ID: 15,
//     Name: 'Projector PlusHD',
//     Price: 750,
//     Current_Inventory: 110,
//     Backorder: 0,
//     Manufacturing: 90,
//     Category: 'Projectors',
//     ImageSrc: 'images/vehicles/15.png',
// }, {
//     ID: 17,
//     Name: 'ExcelRemote IR',
//     Price: 150,
//     Current_Inventory: 650,
//     Backorder: 0,
//     Manufacturing: 190,
//     Category: 'Automation',
//     ImageSrc: 'images/vehicles/17.png',
// }, {
//     ID: 18,
//     Name: 'ExcelRemote BT',
//     Price: 180,
//     Current_Inventory: 310,
//     Backorder: 0,
//     Manufacturing: 0,
//     Category: 'Automation',
//     ImageSrc: 'images/vehicles/18.png',
// }, {
//     ID: 19,
//     Name: 'ExcelRemote IP',
//     Price: 200,
//     Current_Inventory: 0,
//     Backorder: 325,
//     Manufacturing: 225,
//     Category: 'Automation',
//     ImageSrc: 'images/vehicles/19.png',
// }
];
